[theme]
primaryColor="#39FF14"
backgroundColor="#000000"
secondaryBackgroundColor="#1a1a1a"
textColor="#39FF14"
font="serif"
[server]
headless = true
port = 7860
enableCORS = false
enableXsrfProtection = false